### ISSUE TITLE
Meanning of each key from the provided lineclouds json data

### ISSUE THREAD

**Issue by HanzhiC** [Luo1Cheng/LC2WF#4]
Hi, thanks for the nice work.

I would like to customize my own data, so I would like to ask about the meaning of each key from the provided lineclouds json data , e.g., LC2WF_data/LineCloud_0130_P123/BJ39_500_098051_0020.json.

```
junc3DList: vertices of the lineclouds
junc2DList: ?
viewList: ?
edgeList: edges of the lineclouds w.r.t vertex indices
label: ?
objGTJunc3D: vertices of GT wireframe  
objGTSeg3D: ?
line_idx: edges of GT wireframe w.r.t vertex indices
```
I summarize the meaning of some keys, and could you answer what junc2DList, viewList, label, objGTSeg3D mean exactly?

Thanks in advance : )

**Comment by Luo1Cheng** [comment]
junc3DList: N x 3, 3D junctions in world coord system
edgeList: N x 2 (idx1, idx2), edge of the line cloud, idx1/idx2: index of the junc3DList

junc2DList: N x 2, 2D junctions in a certain image/view.
viewList: N x 1, 2D junction No.i corresponds to the image/view viewList[No.i], viewList is 1-based index. This parameter is come from Line3Dpp

label: N x 1, junction No.i corresponds to the junction No.label[i] of the ground-truth wireframe junction. -1 means this junction belongs to noise.
objGTJunc3D: N x 3, ground-truth junction of the 3D wireframe.
objGTSeg3D: N x 6, ground-truth segment of the 3D wireframe. 6 means xyz of two points
line_idx: ground-truth edge of the 3D wireframe.

**Comment by OmarAhmadin** [comment]
> Hi, thanks for the nice work.
> 
> I would like to customize my own data, so I would like to ask about the meaning of each key from the provided lineclouds json data , e.g., LC2WF_data/LineCloud_0130_P123/BJ39_500_098051_0020.json.
> 
> ```
> junc3DList: vertices of the lineclouds
> junc2DList: ?
> viewList: ?
> edgeList: edges of the lineclouds w.r.t vertex indices
> label: ?
> objGTJunc3D: vertices of GT wireframe  
> objGTSeg3D: ?
> line_idx: edges of GT wireframe w.r.t vertex indices
> ```
> 
> I summarize the meaning of some keys, and could you answer what junc2DList, viewList, label, objGTSeg3D mean exactly?
> 
> Thanks in advance : )

Hi @HanzhiC ,

I wonder how did you convert your obj file to such json format?

Thanks!
